server:
  port: 2225

spring:
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 3
      properties:
        linger_ms: 1
        enable_idempotence: true
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    streams:
      application-id: available-cars-app
      replication-factor: 1
      auto-startup: true
      properties:
        processing:
          guarantee: exactly_once
    bootstrap-servers: localhost:9092

available-cars-app:
  topic-name:
    s3-car: s3_car_topic
    car-request: car_request_topic
    rented-cars: rented_cars_topic
    user-exceptions: user_exceptions_topic
